### ISSUE TITLE
[bug] Initialize unsuitable `default` profiles for MSVC compilers after running `pytest tests.py` command.

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/cmake-conan#453]
### Problem Descriptions

Recently, I tried to improve the autodetection of MSVC compilers. This is the [branch](https://github.com/hwhsu1231/cmake-conan/tree/detect-msvc-settings-in-conan2) that I currently work with. I zip this branch into the following zip file:

[cmake-conan-detect-msvc-settings-in-conan2.zip](https://github.com/conan-io/cmake-conan/files/9856750/cmake-conan-detect-msvc-settings-in-conan2.zip)

However, there are two errors after running `pytest tests.py` command. I'm not sure what causes it, but all of these two errors have the following messages. Can Conan Team (@memsharded @czoido ) help me to figure out what happened behind these two errors?

```cmd
Auto detecting your dev setup to initialize the default profile (C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\profiles\default)
WARN: Remotes registry file missing, creating default one in C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\remotes.json
```

1.  CMakeConanTest.test_profile_auto

    <details><summary>Click to expand</summary>

    ```cmd
    --------------------------------- Captured stdout call ----------------------------------
    -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
    -- The CXX compiler identification is MSVC 19.29.30146.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- CMAKE VERSION: 3.24.2
    -- Conan: Automatic detection of conan settings from cmake
    -- Conan: Detected MSVC runtime: dynamic
    -- Conan: Detected MSVC runtime_type: Release
    -- Conan: Settings= -pr=myprofile;-s;build_type=Release;-s;compiler=msvc
    -- Conan: checking conan executable
    -- Conan: Found program C:/Python/Python310/Scripts/conan.exe
    -- Conan: Version found Conan version 1.53.0
    -- Conan executing: C:/Python/Python310/Scripts/conan.exe install . -pr=myprofile -s build_type=Release -s compiler=msvc -g=cmake
    Auto detecting your dev setup to initialize the default profile (C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\profiles\default)
    Found Visual Studio 16
    Default settings
            os=Windows
            os_build=Windows
            arch=x86_64
            arch_build=x86_64
            compiler=Visual Studio
            compiler.version=16
            build_type=Release
    *** You can change them in C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\profiles\default ***
    *** Or override with -s compiler='other' -s ...s***


    Configuration:
    [settings]
    build_type=Release
    compiler=msvc
    compiler.runtime_type=Release
    [options]
    [build_requires]
    [env]

    Traceback (most recent call last):
      File "C:\Python\Python310\lib\site-packages\conans\client\command.py", line 2216, in run    method(args[0][1:])
      File "C:\Python\Python310\lib\site-packages\conans\client\command.py", line 523, in install
        info = self._conan.install(path=args.path_or_reference,
      File "C:\Python\Python310\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper
        return f(api, *args, **kwargs)
      File "C:\Python\Python310\lib\site-packages\conans\client\conan_api.py", line 609, in install
        deps_install(app=self.app,
      File "C:\Python\Python310\lib\site-packages\conans\client\manager.py", line 58, in deps_install
        deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
      File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 128, in load_graph
        deps_graph = self._resolve_graph(root_node, profile_host, profile_build, graph_lock,
      File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 290, in _resolve_graph
        deps_graph = self._load_graph(root_node, check_updates, update,
      File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 411, in _load_graph
        self._recurse_build_requires(graph, builder, check_updates, update, build_mode,
      File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 337, in _recurse_build_requires
        self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
      File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_binaries.py", line 444, in evaluate_graph
        self._compute_package_id(node, default_package_id_mode, default_python_requires_id_mode)
      File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_binaries.py", line 394, in _compute_package_id
        msvc_compatible = conanfile.info.msvc_compatible()
      File "C:\Python\Python310\lib\site-packages\conans\model\info.py", line 597, in msvc_compatible
        visual_version = msvc_version_to_vs_ide_version(version)
      File "C:\Python\Python310\lib\site-packages\conan\tools\microsoft\visual.py", line 45, in msvc_version_to_vs_ide_version
        return _visuals[str(version)]
    KeyError: 'None'

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/hwhsu1231/AppData/Local/Temp/tmphk2p6ooaconans/build/CMakeFiles/CMakeOutput.log".
    --------------------------------- Captured stderr call ----------------------------------
    WARN: Remotes registry file missing, creating default one in C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\remotes.json
    ERROR: 'None'
    CMake Error at conan.cmake:598 (message):
      Conan install failed='1'
    Call Stack (most recent call first):
      conan.cmake:940 (old_conan_cmake_install)
      CMakeLists.txt:8 (conan_cmake_run)
    ```

    </details>

2.  CMakeConanTest.test_settings_removed_from_autodetect

    <details><summary>Click to expand</summary>

    ```cmd
    --------------------------------- Captured stdout call ----------------------------------
    -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
    -- The CXX compiler identification is MSVC 19.29.30146.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Conan: Automatic detection of conan settings from cmake
    -- Conan: Detected MSVC runtime: dynamic
    -- Conan: Detected MSVC runtime_type: Release
    -- Conan: compiler.runtime was added as an argument. Not using the autodetected one.
    -- Conan: Settings= -s;arch=x86_64;-s;build_type=Release;-s;compiler=msvc;-s;compiler.version=192;-s;compiler.runtime_type=Release;-s;compiler.cppstd=14;-s;compiler.runtime=static
    -- Conan: checking conan executable
    -- Conan: Found program C:/Python/Python310/Scripts/conan.exe
    -- Conan: Version found Conan version 1.53.0
    -- Conan executing: C:/Python/Python310/Scripts/conan.exe install . -s arch=x86_64 -s build_type=Release -s compiler=msvc -s compiler.version=192 -s compiler.runtime_type=Release -s compiler.cppstd=14 -s compiler.runtime=static -g=cmake
    Auto detecting your dev setup to initialize the default profile (C:\Users\HWHSU1~1\AppData\Local\Temp\tmp7k1r5ysmconan\.conan\profiles\default)
    Found Visual Studio 16
    Default settings
            os=Windows
            os_build=Windows
            arch=x86_64
            arch_build=x86_64
            compiler=Visual Studio
            compiler.version=16
            build_type=Release
    *** You can change them in C:\Users\HWHSU1~1\AppData\Local\Temp\tmp7k1r5ysmconan\.conan\profiles\default ***
    *** Or override with -s compiler='other' -s ...s***


    Configuration:
    [settings]
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=msvc
    compiler.cppstd=14
    compiler.runtime=static
    compiler.runtime_type=Release
    compiler.version=192
    os=Windows
    os_build=Windows
    [options]
    [build_requires]
    [env]

    conanfile.txt: Installing package
    Requirements
    Packages

    Installing (downloading, building) binaries...
    conanfile.txt: Generator cmake created conanbuildinfo.cmake
    conanfile.txt: Generator txt created conanbuildinfo.txt
    conanfile.txt: Aggregating env generators
    conanfile.txt: Generated conaninfo.txt
    conanfile.txt: Generated graphinfo
    -- Conan: Loading conanbuildinfo.cmake
    -- Conan: Adjusting output directories
    -- Conan: Using cmake global configuration
    -- Conan: Adjusting default RPATHs Conan policies
    -- Conan: Adjusting language standard
    -- Current conanbuildinfo.cmake directory: C:/Users/hwhsu1231/AppData/Local/Temp/tmp3susm1dmconans/build
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/hwhsu1231/AppData/Local/Temp/tmp3susm1dmconans/build/CMakeFiles/CMakeOutput.log".
    --------------------------------- Captured stderr call ----------------------------------
    WARN: Remotes registry file missing, creating default one in C:\Users\HWHSU1~1\AppData\Local\Temp\tmp7k1r5ysmconan\.conan\remotes.json
    CMake Error at CMakeLists.txt:10 (message):
      CONAN_SETTINGS DUPLICATED!
    ```

    </details>

### Debug Log

<details><summary>Click to expand</summary>

```cmd
F:\GitRepo\cmake-conan>pytest tests.py
================================== test session starts ==================================
platform win32 -- Python 3.10.7, pytest-7.1.3, pluggy-1.0.0
rootdir: F:\GitRepo\cmake-conan
collected 37 items

tests.py .................s...F..F............                                     [100%]

======================================= FAILURES ========================================
___________________________ CMakeConanTest.test_profile_auto ____________________________

self = <tests.CMakeConanTest testMethod=test_profile_auto>

    def test_profile_auto(self):
        content = textwrap.dedent("""
            cmake_minimum_required(VERSION 3.9)
            project(FormatOutput CXX)
            message(STATUS "CMAKE VERSION: ${CMAKE_VERSION}")

            set(CONAN_DISABLE_CHECK_COMPILER ON)
            include(conan.cmake)
            conan_cmake_run(BASIC_SETUP
                            PROFILE myprofile
                            PROFILE_AUTO build_type
                            PROFILE_AUTO compiler
                            )

            if(NOT "${CONAN_SETTINGS_BUILD_TYPE}" STREQUAL "${CMAKE_BUILD_TYPE}")
                message(FATAL_ERROR "CONAN_SETTINGS_BUILD_TYPE INCORRECT!")
            endif()
            if("${CONAN_SETTINGS_COMPILER}" STREQUAL "sun-cc")
                message(FATAL_ERROR "CONAN_SETTINGS_COMPILER INCORRECT!")
            endif()
            if("${CONAN_SETTINGS_COMPILER_VERSION}" STREQUAL "12")
                message(FATAL_ERROR "CONAN_SETTINGS_COMPILER_VERSION INCORRECT!")
            endif()
            if("${CONAN_SETTINGS_COMPILER_RUNTIME}" STREQUAL "MTd")
                message(FATAL_ERROR "CONAN_SETTINGS_COMPILER_RUNTIME INCORRECT!")
            endif()
        """)
        save("build/myprofile", textwrap.dedent("""
            [settings]
            build_type=RelWithDebInfo
            compiler=sun-cc
            compiler.version=5.10
        """))
        save("CMakeLists.txt", content)

        os.chdir("build")
>       run("cmake .. %s  -DCMAKE_BUILD_TYPE=Release" % (generator))

tests.py:703:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = 'cmake .. -G "Visual Studio 16 2019"  -DCMAKE_BUILD_TYPE=Release'
ignore_errors = False

    def run(cmd, ignore_errors=False):
        retcode = os.system(cmd)
        if retcode != 0 and not ignore_errors:
>           raise Exception("Command failed: %s" % cmd)
E           Exception: Command failed: cmake .. -G "Visual Studio 16 2019"  -DCMAKE_BUILD_TYPE=Release

tests.py:24: Exception
--------------------------------- Captured stdout call ----------------------------------
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE VERSION: 3.24.2
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Detected MSVC runtime: dynamic
-- Conan: Detected MSVC runtime_type: Release
-- Conan: Settings= -pr=myprofile;-s;build_type=Release;-s;compiler=msvc
-- Conan: checking conan executable
-- Conan: Found program C:/Python/Python310/Scripts/conan.exe
-- Conan: Version found Conan version 1.53.0
-- Conan executing: C:/Python/Python310/Scripts/conan.exe install . -pr=myprofile -s build_type=Release -s compiler=msvc -g=cmake
Auto detecting your dev setup to initialize the default profile (C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\profiles\default)
Found Visual Studio 16
Default settings
        os=Windows
        os_build=Windows
        arch=x86_64
        arch_build=x86_64
        compiler=Visual Studio
        compiler.version=16
        build_type=Release
*** You can change them in C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***


Configuration:
[settings]
build_type=Release
compiler=msvc
compiler.runtime_type=Release
[options]
[build_requires]
[env]

Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\conans\client\command.py", line 2216, in run    method(args[0][1:])
  File "C:\Python\Python310\lib\site-packages\conans\client\command.py", line 523, in install
    info = self._conan.install(path=args.path_or_reference,
  File "C:\Python\Python310\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "C:\Python\Python310\lib\site-packages\conans\client\conan_api.py", line 609, in install
    deps_install(app=self.app,
  File "C:\Python\Python310\lib\site-packages\conans\client\manager.py", line 58, in deps_install
    deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
  File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 128, in load_graph
    deps_graph = self._resolve_graph(root_node, profile_host, profile_build, graph_lock,
  File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 290, in _resolve_graph
    deps_graph = self._load_graph(root_node, check_updates, update,
  File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 411, in _load_graph
    self._recurse_build_requires(graph, builder, check_updates, update, build_mode,
  File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_manager.py", line 337, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_binaries.py", line 444, in evaluate_graph
    self._compute_package_id(node, default_package_id_mode, default_python_requires_id_mode)
  File "C:\Python\Python310\lib\site-packages\conans\client\graph\graph_binaries.py", line 394, in _compute_package_id
    msvc_compatible = conanfile.info.msvc_compatible()
  File "C:\Python\Python310\lib\site-packages\conans\model\info.py", line 597, in msvc_compatible
    visual_version = msvc_version_to_vs_ide_version(version)
  File "C:\Python\Python310\lib\site-packages\conan\tools\microsoft\visual.py", line 45, in msvc_version_to_vs_ide_version
    return _visuals[str(version)]
KeyError: 'None'

-- Configuring incomplete, errors occurred!
See also "C:/Users/hwhsu1231/AppData/Local/Temp/tmphk2p6ooaconans/build/CMakeFiles/CMakeOutput.log".
--------------------------------- Captured stderr call ----------------------------------
WARN: Remotes registry file missing, creating default one in C:\Users\HWHSU1~1\AppData\Local\Temp\tmpah17ti9_conan\.conan\remotes.json
ERROR: 'None'
CMake Error at conan.cmake:598 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  conan.cmake:940 (old_conan_cmake_install)
  CMakeLists.txt:8 (conan_cmake_run)


_________________ CMakeConanTest.test_settings_removed_from_autodetect __________________

self = <tests.CMakeConanTest testMethod=test_settings_removed_from_autodetect>

    def test_settings_removed_from_autodetect(self):
        if platform.system() == "Windows":
            settings_check = "compiler.runtime"
            custom_setting = "{}=static".format(settings_check)
        else:
            settings_check = "compiler.libcxx"
            custom_setting = "{}=libstdc++".format(settings_check)

        content = textwrap.dedent("""
            cmake_minimum_required(VERSION 3.9)
            project(FormatOutput CXX)
            include(conan.cmake)
            conan_cmake_run(BASIC_SETUP
                            SETTINGS {})
            STRING(REGEX MATCHALL "{}" matches "${{settings}}")
            list(LENGTH matches n_matches)
            if(NOT n_matches EQUAL 1)
                message(FATAL_ERROR "CONAN_SETTINGS DUPLICATED!")
            endif()
        """.format(custom_setting, settings_check))
        save("CMakeLists.txt", content)

        os.makedirs("build")
        os.chdir("build")
>       run("cmake .. %s  -DCMAKE_BUILD_TYPE=Release" % (generator))

tests.py:665:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = 'cmake .. -G "Visual Studio 16 2019"  -DCMAKE_BUILD_TYPE=Release'
ignore_errors = False

    def run(cmd, ignore_errors=False):
        retcode = os.system(cmd)
        if retcode != 0 and not ignore_errors:
>           raise Exception("Command failed: %s" % cmd)
E           Exception: Command failed: cmake .. -G "Visual Studio 16 2019"  -DCMAKE_BUILD_TYPE=Release

tests.py:24: Exception
--------------------------------- Captured stdout call ----------------------------------
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Detected MSVC runtime: dynamic
-- Conan: Detected MSVC runtime_type: Release
-- Conan: compiler.runtime was added as an argument. Not using the autodetected one.
-- Conan: Settings= -s;arch=x86_64;-s;build_type=Release;-s;compiler=msvc;-s;compiler.version=192;-s;compiler.runtime_type=Release;-s;compiler.cppstd=14;-s;compiler.runtime=static
-- Conan: checking conan executable
-- Conan: Found program C:/Python/Python310/Scripts/conan.exe
-- Conan: Version found Conan version 1.53.0
-- Conan executing: C:/Python/Python310/Scripts/conan.exe install . -s arch=x86_64 -s build_type=Release -s compiler=msvc -s compiler.version=192 -s compiler.runtime_type=Release -s compiler.cppstd=14 -s compiler.runtime=static -g=cmake
Auto detecting your dev setup to initialize the default profile (C:\Users\HWHSU1~1\AppData\Local\Temp\tmp7k1r5ysmconan\.conan\profiles\default)
Found Visual Studio 16
Default settings
        os=Windows
        os_build=Windows
        arch=x86_64
        arch_build=x86_64
        compiler=Visual Studio
        compiler.version=16
        build_type=Release
*** You can change them in C:\Users\HWHSU1~1\AppData\Local\Temp\tmp7k1r5ysmconan\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***


Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=static
compiler.runtime_type=Release
compiler.version=192
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: C:/Users/hwhsu1231/AppData/Local/Temp/tmp3susm1dmconans/build
-- Configuring incomplete, errors occurred!
See also "C:/Users/hwhsu1231/AppData/Local/Temp/tmp3susm1dmconans/build/CMakeFiles/CMakeOutput.log".
--------------------------------- Captured stderr call ----------------------------------
WARN: Remotes registry file missing, creating default one in C:\Users\HWHSU1~1\AppData\Local\Temp\tmp7k1r5ysmconan\.conan\remotes.json
CMake Error at CMakeLists.txt:10 (message):
  CONAN_SETTINGS DUPLICATED!


================================ short test summary info ================================
FAILED tests.py::CMakeConanTest::test_profile_auto - Exception: Command failed: cmake ....FAILED tests.py::CMakeConanTest::test_settings_removed_from_autodetect - Exception: Com...================== 2 failed, 34 passed, 1 skipped in 248.36s (0:04:08) ==================
```

</details>

**Comment by hwhsu1231** [comment]
I already fix them, so I'll close this issue.
