### ISSUE TITLE
Linux i386 binaries are not available at cmake.org

### ISSUE THREAD

**Issue by db4** [conan-io/cmake-conan#91]
Tried to install `cmake_installer/3.11.3@conan/stable` (arch=x86), got an error:

```
cmake_installer/3.11.3@conan/stable: Building your package in /home/conan/.conan/data/cmake_installer/3.11.3/conan/stable/build/445cf80f611c1d1eda08bde2ebc5066218ca9701
cmake_installer/3.11.3@conan/stable: Configuring sources in /home/conan/.conan/data/cmake_installer/3.11.3/conan/stable/source
cmake_installer/3.11.3@conan/stable: Copying sources to build folder
cmake_installer/3.11.3@conan/stable: Generator txt created conanbuildinfo.txt
cmake_installer/3.11.3@conan/stable: Calling build()
cmake_installer/3.11.3@conan/stable: Downloading: https://cmake.org/files/v3.11/cmake-3.11.3-Linux-i386.tar.gz
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
cmake_installer/3.11.3@conan/stable: 
cmake_installer/3.11.3@conan/stable: ERROR: Package '445cf80f611c1d1eda08bde2ebc5066218ca9701' build failed
cmake_installer/3.11.3@conan/stable: WARN: Build folder /home/conan/.conan/data/cmake_installer/3.11.3/conan/stable/build/445cf80f611c1d1eda08bde2ebc5066218ca9701
Traceback (most recent call last):
  File "build.py", line 26, in <module>
    main()
  File "build.py", line 23, in main
    builder.run()
  File "/usr/local/lib/python2.7/dist-packages/cpt/packager.py", line 376, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "/usr/local/lib/python2.7/dist-packages/cpt/packager.py", line 453, in run_builds
    r.run()
  File "/usr/local/lib/python2.7/dist-packages/cpt/runner.py", line 74, in run
    test_folder=self._test_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 327, in create
    test_build_folder, test_folder, conanfile_path)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/create.py", line 40, in create
    test_build_folder=test_build_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/test.py", line 39, in install_build_and_test
    keep_build=keep_build)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/manager.py", line 280, in install
    installer.install(deps_graph, keep_build)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 259, in install
    self._build(nodes_by_level, deps_graph, keep_build, root_node)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 281, in _build
    self._handle_node_cache(node, package_id, keep_build, processed_package_references)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 298, in _handle_node_cache
    self._build_package(node, package_ref, output, keep_build)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 377, in _build_package
    raise exc
conans.errors.ConanExceptionInUserConanfileMethod: cmake_installer/3.11.3@conan/stable: Error in build() method, line 75
	tools.download(url, dest_file, verify=False)
	NotFoundException: Not found: https://cmake.org/files/v3.11/cmake-3.11.3-Linux-i386.tar.gz
```

**Comment by db4** [comment]
Ah, sorry - it should be posted to [conan-cmake-installer issues](https://github.com/conan-community/conan-cmake-installer/issues) instead!
